# Generated by Django 4.1.5 on 2023-02-24 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0002_remove_employee_department_employee_emp_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dep_manager',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hrapp.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_department',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hrapp.department'),
        ),
    ]
