# Generated by Django 4.1.5 on 2023-02-24 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0004_alter_department_dep_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dep_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrapp.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrapp.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrapp.employee'),
        ),
    ]
