# Generated by Django 4.1.5 on 2023-02-27 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0006_alter_department_dep_manager_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='dbo',
            new_name='DOB',
        ),
    ]
